USE [SAINTA]
GO

/****** Object:  Table [dbo].[SBFDCCONS]    Script Date: 24/08/2025 20:42:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SBFDCCONS](
	[NroUnico] [int] IDENTITY(1,1) NOT NULL,
	[NLinea] [int] NOT NULL,
	[Descripcion] [varchar](70) NOT NULL,
	[Monto] [decimal](28, 4) NOT NULL,
	[CreatedAt] [datetime] NULL,
	[UpdatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[NroUnico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SBFDCCONS] ADD  DEFAULT ((0)) FOR [NLinea]
GO

ALTER TABLE [dbo].[SBFDCCONS] ADD  DEFAULT ((0)) FOR [Monto]
GO

ALTER TABLE [dbo].[SBFDCCONS] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO


