USE [admin]
GO

/****** Object:  Table [dbo].[SACIUDAD]    Script Date: 24/08/2025 9:50:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SACIUDAD](
	[Ciudad] [int] NOT NULL,
	[Descrip] [nvarchar](40) NOT NULL,
	[Estado] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Ciudad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SACIUDAD]  WITH CHECK ADD FOREIGN KEY([Estado])
REFERENCES [dbo].[SAESTADO] ([Estado])
ON DELETE CASCADE
GO


