USE [admin]
GO

/****** Object:  Table [dbo].[SBFDCPER]    Script Date: 24/08/2025 20:43:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SBFDCPER](
	[NroUnico] [int] IDENTITY(1,1) NOT NULL,
	[Periodo] [varchar](7) NOT NULL,
	[SaldoA] [decimal](28, 4) NOT NULL,
	[CreatedAt] [datetime] NULL,
	[UpdatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[NroUnico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SBFDCPER] ADD  DEFAULT ((0)) FOR [SaldoA]
GO

ALTER TABLE [dbo].[SBFDCPER] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO


