USE [admin]
GO

/****** Object:  Table [dbo].[SSFMTS]    Script Date: 24/08/2025 20:50:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SSFMTS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FmtNro] [int] NOT NULL,
	[FmtTit] [varchar](70) NULL,
	[FmtNme] [varchar](70) NULL,
	[CreatedAt] [datetime] NULL,
	[UpdatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SSFMTS] ADD  DEFAULT ((0)) FOR [FmtNro]
GO

ALTER TABLE [dbo].[SSFMTS] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO


