USE [admin]
GO

/****** Object:  Table [dbo].[SSDTAA]    Script Date: 24/08/2025 20:49:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SSDTAA](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CodArch] [int] NOT NULL,
	[CodData] [varchar](30) NOT NULL,
	[IndDta] [int] NOT NULL,
	[TipDta] [varchar](50) NULL,
	[CreatedAt] [datetime] NULL,
	[UpdatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SSDTAA] ADD  DEFAULT ((0)) FOR [CodArch]
GO

ALTER TABLE [dbo].[SSDTAA] ADD  DEFAULT ((0)) FOR [IndDta]
GO

ALTER TABLE [dbo].[SSDTAA] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO


