USE [SAINTA]
GO

/****** Object:  Table [dbo].[SAESTADO]    Script Date: 24/08/2025 10:18:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SAESTADO](
	[Estado] [int] NOT NULL,
	[Descrip] [nvarchar](40) NOT NULL,
	[Pais] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Estado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SAESTADO]  WITH CHECK ADD FOREIGN KEY([Pais])
REFERENCES [dbo].[SAPAIS] ([Pais])
ON DELETE CASCADE
GO


