USE [admin]
GO

/****** Object:  Table [dbo].[SARGOCAT]    Script Date: 24/08/2025 20:26:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SARGOCAT](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CodInst] [int] NOT NULL,
	[TipoRgo] [int] NOT NULL,
	[NroUnico] [int] NOT NULL,
	[Desde] [decimal](28, 4) NOT NULL,
	[Hasta] [decimal](28, 4) NOT NULL,
	[Monto] [decimal](28, 4) NOT NULL,
	[CreatedAt] [datetime] NULL,
	[UpdatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SARGOCAT] ADD  DEFAULT ((0)) FOR [CodInst]
GO

ALTER TABLE [dbo].[SARGOCAT] ADD  DEFAULT ((0)) FOR [TipoRgo]
GO

ALTER TABLE [dbo].[SARGOCAT] ADD  DEFAULT ((0)) FOR [NroUnico]
GO

ALTER TABLE [dbo].[SARGOCAT] ADD  DEFAULT ((0)) FOR [Desde]
GO

ALTER TABLE [dbo].[SARGOCAT] ADD  DEFAULT ((0)) FOR [Hasta]
GO

ALTER TABLE [dbo].[SARGOCAT] ADD  DEFAULT ((0)) FOR [Monto]
GO

ALTER TABLE [dbo].[SARGOCAT] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO


