USE [admin]
GO

/****** Object:  Table [dbo].[SFTFLD]    Script Date: 24/08/2025 20:48:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SFTFLD](
	[folderid] [int] IDENTITY(1,1) NOT NULL,
	[foldername] [varchar](60) NOT NULL,
	[parentid] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[folderid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


