USE [admin]
GO

/****** Object:  Table [dbo].[SAMUNICIPIO]    Script Date: 24/08/2025 13:41:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SAMUNICIPIO](
	[Municipio] [int] NOT NULL,
	[Descrip] [nvarchar](40) NOT NULL,
	[Ciudad] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Municipio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SAMUNICIPIO]  WITH CHECK ADD FOREIGN KEY([Ciudad])
REFERENCES [dbo].[SACIUDAD] ([Ciudad])
ON DELETE CASCADE
GO


