USE [admin]
GO

/****** Object:  Table [dbo].[SACLICNV]    Script Date: 24/08/2025 9:50:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SACLICNV](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CodConv] [varchar](10) NOT NULL,
	[CodClie] [varchar](15) NOT NULL,
	[CreatedAt] [datetime] NULL,
	[UpdatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SACLICNV] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO


