USE [SAINTA]
GO

/****** Object:  Table [dbo].[SAAUDITEM]    Script Date: 24/08/2025 9:49:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SAAUDITEM](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Tipo] [int] NOT NULL,
	[Identidad] [varchar](70) NOT NULL,
	[Sequence] [decimal](28, 4) NOT NULL,
	[Refere] [decimal](28, 4) NOT NULL,
	[Value] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SAAUDITEM] ADD  DEFAULT ((0)) FOR [Tipo]
GO

ALTER TABLE [dbo].[SAAUDITEM] ADD  DEFAULT ((0)) FOR [Sequence]
GO

ALTER TABLE [dbo].[SAAUDITEM] ADD  DEFAULT ((0)) FOR [Refere]
GO


