USE [SAINTA]
GO

/****** Object:  Table [dbo].[SATAXPRD]    Script Date: 24/08/2025 20:34:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SATAXPRD](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CodProd] [varchar](15) NOT NULL,
	[CodTaxs] [varchar](10) NOT NULL,
	[Monto] [decimal](28, 4) NOT NULL,
	[EsPorct] [smallint] NOT NULL,
	[CreatedAt] [datetime] NULL,
	[UpdatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SATAXPRD] ADD  DEFAULT ((0)) FOR [Monto]
GO

ALTER TABLE [dbo].[SATAXPRD] ADD  DEFAULT ((0)) FOR [EsPorct]
GO

ALTER TABLE [dbo].[SATAXPRD] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO


