name: saint_flutter
description: "Flutter multi-tenant offline-first MVP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  go_router: ^14.2.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  path: ^1.9.0
  open_filex: ^4.5.0
  workmanager: ^0.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.24
  jose: ^0.3.3
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.9.5
  drift_dev: ^2.17.0

flutter:
  uses-material-design: true
  generate: true
