SELECT R.CODSUCU, R.PERIODO, FLOOR(SUM(R.NROFACTS)) NROFACTS, SUM(R.MTOFACTS) MTOFACTS, FLOOR(SUM(R.NRODEVOL)) NRODEVOL, SUM(R.MTODEVOL) MTODEVOL, SUM(R.CREDITO) CREDITO, SUM(R.CONTADO) CONTADO, 
                  SUM(R.MTOTOTAL) MTOTOTAL, SUM(R.COSTO) COSTO, SUM(R.UTILIDAD) UTILIDAD, SUM(R.MTORETENIMP) MTORETENIMP
FROM     (SELECT F.CODSUCU, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, SUM(IIF(F.TIPOFAC = 'A', 1, 0)) NROFACTS, SUM(IIF(F.TIPOFAC = 'A', F.MTOTOTAL, 0)) MTOFACTS, SUM(IIF(F.TIPOFAC = 'B', 1, 0)) NRODEVOL, SUM(IIF(F.TIPOFAC = 'B', 
                                    F.MTOTOTAL, 0)) MTODEVOL, SUM(F.SIGNO * F.CREDITO) CREDITO, SUM(F.SIGNO * F.CONTADO) CONTADO, SUM(F.SIGNO * F.MTOTOTAL) MTOTOTAL, SUM(F.SIGNO * (F.COSTOPRD + F.COSTOSRV)) COSTO, 
                                    SUM(F.SIGNO * (F.MONTO - (F.COSTOPRD + F.COSTOSRV))) UTILIDAD, SUM(F.SIGNO * F.CANCELI) MTORETENIMP
                  FROM      SAFACT F
                  WHERE   F.TIPOFAC IN ('A', 'B')
                  GROUP BY F.CODSUCU, FORMAT(F.FECHAE, 'yyyy-MM')) R
GROUP BY R.CODSUCU, R.PERIODO