SELECT R.CODCLIE, R.PERIODO, FLOOR(SUM(R.NROFACTS)) NROFACTS, SUM(R.MTOFACTS) MTOFACTS, FLOOR(SUM(R.NRODEVOL)) NRODEVOL, SUM(R.MTODEVOL) MTODEVOL, SUM(R.CREDITO) CREDITO, SUM(R.CONTADO) CONTADO, 
                  SUM(R.MTOTOTAL) MTOTOTAL, SUM(R.COSTO) COSTO, SUM(R.UTILIDAD) UTILIDAD, SUM(R.MTORETENIMP) MTORETENIMP, FLOOR(SUM(R.NROPAGOS)) NROPAGOS, SUM(R.MTOPAGOS) MTOPAGOS, FLOOR(SUM(R.NRONDEBITO)) 
                  NRONDEBITO, SUM(R.MTONDEBITO) MTONDEBITO, FLOOR(SUM(R.NRONCREDITO)) NRONCREDITO, SUM(R.MTONCREDITO) MTONCREDITO
FROM     (SELECT F.CODCLIE, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, SUM(IIF(F.TIPOFAC = 'A', 1, 0)) NROFACTS, SUM(IIF(F.TIPOFAC = 'A', F.MTOTOTAL, 0)) MTOFACTS, SUM(IIF(F.TIPOFAC = 'B', 1, 0)) NRODEVOL, SUM(IIF(F.TIPOFAC = 'B', 
                                    F.MTOTOTAL, 0)) MTODEVOL, SUM(F.CREDITO) CREDITO, SUM(F.CONTADO) CONTADO, SUM(F.MTOTOTAL) MTOTOTAL, SUM(F.COSTOPRD + F.COSTOSRV) COSTO, SUM(F.MONTO - (F.COSTOPRD + F.COSTOSRV)) UTILIDAD, 
                                    SUM(F.CANCELI) MTORETENIMP, 0 NROPAGOS, 0 MTOPAGOS, 0 NRONDEBITO, 0 MTONDEBITO, 0 NRONCREDITO, 0 MTONCREDITO
                  FROM      SAFACT F
                  WHERE   F.TIPOFAC IN ('A', 'B')
                  GROUP BY F.CODCLIE, FORMAT(F.FECHAE, 'yyyy-MM')
                  UNION ALL
                  SELECT F.CODCLIE, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, 0 NROFACTS, 0 MTOFACTS, 0 NRODEVOL, 0 MTODEVOL, 0 CREDITO, 0 CONTADO, 0 MTOTOTAL, 0 COSTO, 0 UTILIDAD, SUM(F.CANCELI) MTORETENIMP, 
                                    SUM(IIF(SUBSTRING(F.TIPOCXC, 1, 1) IN ('4'), 1, 0)) NROPAGOS, SUM(IIF(SUBSTRING(F.TIPOCXC, 1, 1) IN ('4'), 1, 0) * F.MONTO) MTOPAGOS, SUM(IIF(SUBSTRING(F.TIPOCXC, 1, 1) IN ('2'), 1, 0)) NRONDEBITO, 
                                    SUM(IIF(SUBSTRING(F.TIPOCXC, 1, 1) IN ('2'), 1, 0) * F.MONTO) MTONDEBITO, SUM(IIF(SUBSTRING(F.TIPOCXC, 1, 1) IN ('3', '8'), 1, 0)) NRONCREDITO, SUM(IIF(SUBSTRING(F.TIPOCXC, 1, 1) IN ('3', '8'), 1, 0) * F.MONTO) 
                                    MTONCREDITO
                  FROM     SAACXC F
                  WHERE  SUBSTRING(F.TIPOCXC, 1, 1) IN ('4', '2', '3', '8')
                  GROUP BY F.CODCLIE, FORMAT(F.FECHAE, 'yyyy-MM')) R
GROUP BY R.CODCLIE, R.PERIODO