SELECT R.CODTARJ, R.PERIODO, SUM(R.MTOVENTAS) MTOVENTAS, SUM(R.IMPUESTO) IMPUESTO, SUM(R.RETENCT) MTORETENIMP, SUM(R.MTOINGRESO) MTOINGRESO
FROM     (SELECT I.CODTARJ, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, SUM(I.MONTO) MTOVENTAS, SUM(F.SIGNO * I.IMPUESTO) IMPUESTO, SUM(F.SIGNO * I.RETENCT) RETENCT, SUM(F.SIGNO * (I.MONTO - I.IMPUESTO - I.RETENCT)) 
                                    MTOINGRESO
                  FROM      SAIPAVTA I INNER JOIN
                                    SATARJ T ON (T .CODTARJ = I.CODTARJ) INNER JOIN
                                    SAFACT F ON (F.CODSUCU = I.CODSUCU) AND (F.TIPOFAC = I.TIPOFAC) AND (F.NUMEROD = I.NUMEROD)
                  GROUP BY I.CODTARJ, FORMAT(F.FECHAE, 'yyyy-MM')
                  UNION ALL
                  SELECT I.CODTARJ, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, SUM(I.MONTO), SUM(I.IMPUESTO), SUM(I.RETENCT), SUM(I.MONTO - I.IMPUESTO - I.RETENCT) MTOINGRESO
                  FROM     SAIPACXC I INNER JOIN
                                    SAACXC F ON (F.NROUNICO = I.NROPPAL)
                  GROUP BY I.CODTARJ, FORMAT(F.FECHAE, 'yyyy-MM')) R
GROUP BY R.CODTARJ, R.PERIODO