SELECT R.CODPROD, R.PERIODO, IIF(R.ESUNID = 0, P.UNIDAD, P.UNDEMPAQ) UNIDAD, SUM(R.EXINICIAL) EXINICIAL, SUM(R.CNTVENTAS) CNTVENTAS, SUM(R.MTOVENTAS) MTOVENTAS, SUM(R.COSTOVTAS) COSTO, SUM(R.UTILIDAD) 
                  UTILIDAD, SUM(R.CNTCOMPRAS) CNTCOMPRA, SUM(R.MTOCOMPRAS) MTOCOMPRA, SUM(R.CNTCARGOS) CNTCARGOS, SUM(R.MTOCARGOS) MTOCARGOS, SUM(R.CNTDESCARG) CNTDESCARG, SUM(R.MTODESCARG) 
                  MTODESCARG, SUM(R.EXFINAL) EXFINAL
FROM     (SELECT I.CODPROD, FORMAT(CAST(I.PERIODO + '01' AS DATE), 'yyyy-MM') PERIODO, 0 AS ESUNID, SUM(I.EXINICIAL) EXINICIAL, 0 CNTVENTAS, 0 MTOVENTAS, 0 COSTOVTAS, 0 UTILIDAD, 0 CNTCOMPRAS, 0 MTOCOMPRAS, 
                                    0 CNTCARGOS, 0 MTOCARGOS, 0 CNTDESCARG, 0 MTODESCARG, SUM(I.EXFINAL) EXFINAL
                  FROM      SAINITI I
                  GROUP BY I.CODPROD, I.PERIODO
                  UNION ALL
                  SELECT I.CODPROD, FORMAT(CAST(I.PERIODO + '01' AS DATE), 'yyyy-MM') PERIODO, 1 AS ESUNID, SUM(I.EXUNDINI) EXINICIAL, 0 CNTVENTAS, 0 MTOVENTAS, 0 COSTOVTAS, 0 UTILIDAD, 0 CNTCOMPRAS, 0 MTOCOMPRAS, 
                                    0 CNTCARGOS, 0 MTOCARGOS, 0 CNTDESCARG, 0 MTODESCARG, SUM(I.EXUNDFINAL) EXFINAL
                  FROM     SAINITI I
                  GROUP BY I.CODPROD, I.PERIODO
                  UNION ALL
                  SELECT I.CODITEM CODPROD, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, ESUNID, 0 EXINICIAL, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD) CNTVENTAS, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.PRECIO) MTOVENTAS, 
                                    SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.COSTO) COSTOVTAS, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * (I.PRECIO - I.COSTO)) UTILIDAD, 0 CNTCOMPRAS, 0 MTOCOMPRAS, 0 CNTCARGOS, 0 MTOCARGOS, 
                                    0 CNTDESCARG, 0 MTODESCARG, 0 EXFINAL
                  FROM     SAITEMFAC I INNER JOIN
                                    SAFACT F ON I.CODSUCU = F.CODSUCU AND I.TIPOFAC = F.TIPOFAC AND I.NUMEROD = F.NUMEROD
                  WHERE  (F.TIPOFAC IN ('A', 'B')) AND (I.NROLINEAC = 0) AND (I.ESSERV = 0)
                  GROUP BY I.CODITEM, I.ESUNID, FORMAT(F.FECHAE, 'yyyy-MM')
                  UNION ALL
                  SELECT I.CODITEM CODPROD, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, ESUNID, 0 EXINICIAL, 0 CNTVENTAS, 0 MTOVENTAS, 0 COSTOVTAS, 0 UTILIDAD, SUM(IIF(F.TIPOCOM = 'H', 1, - 1) * I.CANTIDAD) CNTCOMPRAS, 
                                    SUM(IIF(F.TIPOCOM = 'I', 1, - 1) * I.CANTIDAD) MTOCOMPRAS, 0 CNTCARGOS, 0 MTOCARGOS, 0 CNTDESCARG, 0 MTODESCARG, 0 EXFINAL
                  FROM     SAITEMCOM I INNER JOIN
                                    SACOMP F ON I.CODSUCU = F.CODSUCU AND I.TIPOCOM = F.TIPOCOM AND I.NUMEROD = F.NUMEROD
                  WHERE  (F.TIPOCOM IN ('H', 'I')) AND (I.ESSERV = 0)
                  GROUP BY I.CODITEM, I.ESUNID, FORMAT(F.FECHAE, 'yyyy-MM')
                  UNION ALL
                  SELECT I.CODITEM CODPROD, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, ESUNID ESUNID, 0 EXINICIAL, 0 CNTVENTAS, 0 MTOVENTAS, 0 COSTO, 0 UTILIDAD, 0 CNTCOMPRAS, 0 MTOCOMPRAS, SUM(IIF(F.TIPOOPI = 'O', 1, - 1) 
                                    * I.CANTIDAD) CNTCARGOS, SUM(IIF(F.TIPOOPI = 'O', 1, - 1) * I.CANTIDAD) MTOCARGOS, SUM(IIF(F.TIPOOPI = 'P', 1, - 1) * I.CANTIDAD) CNTDESCARG, SUM(IIF(F.TIPOOPI = 'P', 1, - 1) * I.CANTIDAD) MTODESCARG, 
                                    0 EXFINAL
                  FROM     SAITEMOPI I INNER JOIN
                                    SAOPEI F ON I.CODSUCU = F.CODSUCU AND I.TIPOOPI = F.TIPOOPI AND I.NUMEROD = F.NUMEROD
                  WHERE  (F.TIPOOPI IN ('O', 'P')) AND (I.ESSERV = 0)
                  GROUP BY I.CODITEM, I.ESUNID, FORMAT(F.FECHAE, 'yyyy-MM')) R INNER JOIN
                  SAPROD P ON P.CODPROD = R.CODPROD
WHERE  R.ESUNID <= P.ESEMPAQUE
GROUP BY R.CODPROD, R.PERIODO, R.ESUNID, P.UNIDAD, P.UNDEMPAQ