SELECT R.CODVEND, R.PERIODO, SUM(R.MTOVENTAS) MTOVENTAS, SUM(R.COSTO) COSTO, SUM(R.UTILIDAD) UTILIDAD, SUM(R.MTOINGRESO) MTOINGRESO, SUM(R.MTOCOMIVTA) MTOCOMIVTA, SUM(R.MTOCOMICOB) MTOCOMICOB
FROM     (SELECT I.CODVEND, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.PRECIO) MTOVENTAS, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.COSTO) COSTO, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) 
                                    * I.CANTIDAD * (I.PRECIO - I.COSTO)) UTILIDAD, SUM(0) MTOINGRESO, SUM(0) MTOCOMIVTA, SUM(0) MTOCOMICOB
                  FROM      SAITEMFAC I INNER JOIN
                                    SAFACT F ON (I.CODSUCU = F.CODSUCU) AND (I.TIPOFAC = F.TIPOFAC) AND (I.NUMEROD = F.NUMEROD) AND (I.NROLINEAC = 0)
                  WHERE   F.TIPOFAC IN ('A', 'B')
                  GROUP BY I.CODVEND, FORMAT(F.FECHAE, 'yyyy-MM')) R
GROUP BY R.CODVEND, R.PERIODO