SELECT R.CODSUCU, R.PERIODO, FLOOR(SUM(R.NROCOMPS)) NROCOMPS, SUM(R.MTOCOMPRA) MTOCOMPRA, FLOOR(SUM(R.NRODEVOL)) NRODEVOL, SUM(R.MTODEVOL) MTODEVOL, SUM(R.CREDITO) CREDITO, SUM(R.CONTADO) 
                  CONTADO, SUM(R.MTOTOTAL) MTOTOTAL, SUM(R.MTORETIVA) MTORETIVA, SUM(R.MTORETIMP) MTORETIMP
FROM     (SELECT C.CODSUCU, FORMAT(C.FECHAE, 'yyyy-MM-dd') PERIODO, SUM(IIF(C.TIPOCOM = 'H', 1, 0)) NROCOMPS, SUM(IIF(C.TIPOCOM = 'H', C.MTOTOTAL, 0)) MTOCOMPRA, SUM(IIF(C.TIPOCOM = 'I', 1, 0)) NRODEVOL, 
                                    SUM(IIF(C.TIPOCOM = 'I', C.MTOTOTAL, 0)) MTODEVOL, SUM(C.SIGNO * C.CREDITO) CREDITO, SUM(C.SIGNO * C.CONTADO) CONTADO, SUM(C.SIGNO * C.MTOTOTAL) MTOTOTAL, SUM(C.SIGNO * C.CANCELI) MTORETIMP, 
                                    SUM(C.SIGNO * C.RETENIVA) MTORETIVA
                  FROM      SACOMP C
                  WHERE   C.TIPOCOM IN ('H', 'I')
                  GROUP BY C.CODSUCU, FORMAT(C.FECHAE, 'yyyy-MM-dd')) R
GROUP BY R.CODSUCU, R.PERIODO