SELECT R.CODPROV, P.DESCRIP, R.PERIODO, FLOOR(SUM(R.NROCOMPS)) NROCOMPS, SUM(R.MTOCOMPRA) MTOCOMPRA, FLOOR(SUM(R.NRODEVOL)) NRODEVOL, SUM(R.MTODEVOL) MTODEVOL, SUM(R.CREDITO) CREDITO, 
                  SUM(R.CONTADO) CONTADO, SUM(R.MTORETENIMP) MTORETENIMP, FLOOR(SUM(R.NROPAGOS)) NROPAGOS, SUM(R.MTOPAGOS) MTOPAGOS, FLOOR(SUM(R.NRONDEBITO)) NRONDEBITO, SUM(R.MTONDEBITO) MTONDEBITO, 
                  FLOOR(SUM(R.NRONCREDITO)) NRONCREDITO, SUM(R.MTONCREDITO) MTONCREDITO
FROM     (SELECT C.CODPROV, FORMAT(C.FECHAE, 'yyyy-MM') PERIODO, SUM(IIF(C.TIPOCOM = 'H', 1, 0)) NROCOMPS, SUM(IIF(C.TIPOCOM = 'H', C.MTOTOTAL, 0)) MTOCOMPRA, SUM(IIF(C.TIPOCOM = 'I', 1, 0)) NRODEVOL, SUM(IIF(C.TIPOCOM = 'I', 
                                    C.MTOTOTAL, 0)) MTODEVOL, SUM(C.CREDITO) CREDITO, SUM(C.CONTADO) CONTADO, SUM(C.CANCELI) MTORETENIMP, 0 NROPAGOS, 0 MTOPAGOS, 0 NRONDEBITO, 0 MTONDEBITO, 0 NRONCREDITO, 
                                    0 MTONCREDITO
                  FROM      SACOMP C
                  WHERE   C.TIPOCOM IN ('H', 'I')
                  GROUP BY C.CODPROV, FORMAT(C.FECHAE, 'yyyy-MM')
                  UNION ALL
                  SELECT P.CODPROV, FORMAT(P.FECHAE, 'yyyy-MM') PERIODO, 0 NROCOMPS, 0 MTOCOMPRA, 0 NRODEVOL, 0 MTODEVOL, 0 CREDITO, 0 CONTADO, SUM(P.CANCELI) MTORETENIMP, SUM(IIF(SUBSTRING(P.TIPOCXP, 1, 1) IN ('4'), 1, 0)) 
                                    NROPAGOS, SUM(IIF(SUBSTRING(P.TIPOCXP, 1, 1) IN ('4'), 1, 0) * P.MONTO) MTOPAGOS, SUM(IIF(SUBSTRING(P.TIPOCXP, 1, 1) IN ('3'), 1, 0)) NRONDEBITO, SUM(IIF(SUBSTRING(P.TIPOCXP, 1, 1) IN ('3'), 1, 0) * P.MONTO) 
                                    MTONDEBITO, SUM(IIF(SUBSTRING(P.TIPOCXP, 1, 1) IN ('2', '8'), 1, 0)) NRONCREDITO, SUM(IIF(SUBSTRING(P.TIPOCXP, 1, 1) IN ('2', '8'), 1, 0) * P.MONTO) MTONCREDITO
                  FROM     SAACXP P
                  WHERE  SUBSTRING(P.TIPOCXP, 1, 1) IN ('4', '2', '3', '8')
                  GROUP BY P.CODPROV, FORMAT(P.FECHAE, 'yyyy-MM')) R INNER JOIN
                  SAPROV P ON P.CODPROV = R.CODPROV
GROUP BY R.CODPROV, R.PERIODO, P.DESCRIP