SELECT R.CODSERV, R.PERIODO, SUM(R.CNTVENTAS) CNTVENTAS, SUM(R.MTOVENTAS) MTOVENTAS, SUM(R.COSTOVTAS) COSTO, SUM(R.UTILIDAD) UTILIDAD, SUM(R.CNTCOMPRAS) CNTCOMPRA, SUM(R.MTOCOMPRAS) MTOCOMPRA, 
                  SUM(R.CNTCARGOS) CNTCARGOS, SUM(R.MTOCARGOS) MTOCARGOS, SUM(R.CNTDESCARG) CNTDESCARG, SUM(R.MTODESCARG) MTODESCARG
FROM     (SELECT I.CODITEM CODSERV, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.CANTMAYOR) CNTVENTAS, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.CANTMAYOR * I.PRECIO) 
                                    MTOVENTAS, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.CANTMAYOR * I.COSTO) COSTOVTAS, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.CANTMAYOR * (I.PRECIO - I.COSTO)) UTILIDAD, 0 CNTCOMPRAS, 
                                    0 MTOCOMPRAS, 0 CNTCARGOS, 0 MTOCARGOS, 0 CNTDESCARG, 0 MTODESCARG
                  FROM      SAITEMFAC I INNER JOIN
                                    SAFACT F ON I.CODSUCU = F.CODSUCU AND I.TIPOFAC = F.TIPOFAC AND I.NUMEROD = F.NUMEROD
                  WHERE   (F.TIPOFAC IN ('A', 'B')) AND (I.ESSERV = 1)
                  GROUP BY I.CODITEM, FORMAT(F.FECHAE, 'yyyy-MM')
                  UNION ALL
                  SELECT I.CODITEM CODSERV, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, 0 CNTVENTAS, 0 MTOVENTAS, 0 COSTOVTAS, 0 UTILIDAD, SUM(IIF(F.TIPOCOM = 'H', 1, - 1) * I.CANTIDAD) CNTCOMPRAS, SUM(IIF(F.TIPOCOM = 'I', 1, - 1) 
                                    * I.CANTIDAD) MTOCOMPRAS, 0 CNTCARGOS, 0 MTOCARGOS, 0 CNTDESCARG, 0 MTODESCARG
                  FROM     SAITEMCOM I INNER JOIN
                                    SACOMP F ON I.CODSUCU = F.CODSUCU AND I.TIPOCOM = F.TIPOCOM AND I.NUMEROD = F.NUMEROD
                  WHERE  (F.TIPOCOM IN ('H', 'I')) AND (I.ESSERV = 1)
                  GROUP BY I.CODITEM, FORMAT(F.FECHAE, 'yyyy-MM')
                  UNION ALL
                  SELECT I.CODITEM CODSERV, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, 0 CNTVENTAS, 0 MTOVENTAS, 0 COSTO, 0 UTILIDAD, 0 CNTCOMPRAS, 0 MTOCOMPRAS, SUM(IIF(F.TIPOOPI = 'O', 1, - 1) * I.CANTIDAD) CNTCARGOS, 
                                    SUM(IIF(F.TIPOOPI = 'O', 1, - 1) * I.CANTIDAD) MTOCARGOS, SUM(IIF(F.TIPOOPI = 'P', 1, - 1) * I.CANTIDAD) CNTDESCARG, SUM(IIF(F.TIPOOPI = 'P', 1, - 1) * I.CANTIDAD) MTODESCARG
                  FROM     SAITEMOPI I INNER JOIN
                                    SAOPEI F ON I.CODSUCU = F.CODSUCU AND I.TIPOOPI = F.TIPOOPI AND I.NUMEROD = F.NUMEROD
                  WHERE  (F.TIPOOPI IN ('O', 'P')) AND (I.ESSERV = 1)
                  GROUP BY I.CODITEM, FORMAT(F.FECHAE, 'yyyy-MM')) R
GROUP BY R.CODSERV, R.PERIODO