SELECT R.CODMECA, R.PERIODO, FORMAT(CONVERT(DATE, R.PERIODO + '-01'), 'MMM-yyyy', 'es-US') AS MES, SUM(R.CNTVENTAS) CNTVENTAS, SUM(R.MTOVENTAS) MTOVENTAS, SUM(R.COSTO) COSTO, SUM(R.UTILIDAD) UTILIDAD, 
                  SUM(R.COMISION) COMISION
FROM     (SELECT I.CODMECA, FORMAT(F.FECHAE, 'yyyy-MM') PERIODO, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.CANTMAYOR) CNTVENTAS, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.CANTMAYOR * I.PRECIO) MTOVENTAS, 
                                    SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.CANTMAYOR * I.COSTO) COSTO, SUM(IIF(F.TIPOFAC = 'A', 1, - 1) * I.CANTIDAD * I.CANTMAYOR * (I.PRECIO - I.COSTO)) UTILIDAD, SUM(0) MTOINGRESO, SUM(IIF(F.TIPOFAC = 'A', 
                                    1, - 1) * I.CANTIDAD * I.CANTMAYOR * (M.Monto + IIF(M.DEsComi = 0, 0, 1) * M.PorctUtil * (I.PRECIO - I.COSTO) / 100 + ISNULL(C.MONTO, 0) * I.PRECIO / 100)) COMISION
                  FROM      SAITEMFAC I INNER JOIN
                                    SAFACT F ON (I.CODSUCU = F.CODSUCU) AND (I.TIPOFAC = F.TIPOFAC) AND (I.NUMEROD = F.NUMEROD) INNER JOIN
                                    SAMECA M ON (M.CODMECA = I.CODMECA) LEFT JOIN
                                        (SELECT CODMECA, NROUNICO, MONTO
                                         FROM      SACMEC) C ON (C.CODMECA = I.CODMECA) AND (C.NROUNICO = I.TIPOPVP)
                  WHERE   (F.TIPOFAC IN ('A', 'B')) AND (I.ESSERV = 1) AND NOT (I.CODMECA IS NULL)
                  GROUP BY I.CODMECA, FORMAT(F.FECHAE, 'yyyy-MM')) R
GROUP BY R.CODMECA, R.PERIODO