SELECT PA.CODPROD, PA.CODALTE, PA.CANTIDAD, PA.ESUNID, PA.ESSERV, PA.NROUNICO, PA.ESFIJO, (CASE WHEN PA.ESSERV = 0 THEN PR.CODINST ELSE SR.CODINST END) AS CODINST, 
                  (CASE WHEN PA.ESSERV = 0 THEN PR.DESCRIP ELSE SR.DESCRIP END) AS DESCRIP, (CASE WHEN PA.ESSERV = 0 THEN PR.DESCRIP2 ELSE SR.DESCRIP2 END) AS DESCRIP2, 
                  (CASE WHEN PA.ESSERV = 0 THEN PR.DESCRIP3 ELSE SR.DESCRIP3 END) AS DESCRIP3, (CASE WHEN PA.ESSERV = 0 THEN PR.ESEMPAQUE ELSE 0 END) AS ESEMPAQUE, 
                  (CASE WHEN PA.ESSERV = 0 THEN PR.CANTEMPAQ ELSE 0 END) AS CANTEMPAQ, (CASE WHEN PA.ESSERV = 0 THEN PR.DESVENCE ELSE 0 END) AS DESVENCE, (CASE WHEN PA.ESSERV = 0 THEN PR.COSTACT ELSE SR.COSTO END) 
                  AS COSTACT, (CASE WHEN PA.ESSERV = 0 THEN PR.COSTPRO ELSE SR.COSTO END) AS COSTPRO, (CASE WHEN PA.ESSERV = 0 THEN PR.COSTANT ELSE SR.COSTO END) AS COSTANT, 
                  (CASE WHEN PA.ESSERV = 0 THEN IIF(PR.FACTOR = 0, 1, PR.FACTOR) ELSE 1 END) AS FACTOR, (CASE WHEN PA.ESSERV = 0 THEN 0 ELSE SR.ESPORCOST END) AS ESPORCOST, 
                  (CASE WHEN PA.ESSERV = 0 THEN PR.PRECIO1 ELSE SR.PRECIO1 END) AS PRECIO1, (CASE WHEN PA.ESSERV = 0 THEN PR.PRECIO2 ELSE SR.PRECIO2 END) AS PRECIO2, 
                  (CASE WHEN PA.ESSERV = 0 THEN PR.PRECIO3 ELSE SR.PRECIO3 END) AS PRECIO3, (CASE WHEN PA.ESSERV = 0 THEN PR.PRECIOU ELSE 0 END) AS PRECIOU1, (CASE WHEN PA.ESSERV = 0 THEN PR.PrecioU2 ELSE 0 END) 
                  AS PRECIOU2, (CASE WHEN PA.ESSERV = 0 THEN PR.PrecioU3 ELSE 0 END) AS PRECIOU3, (CASE WHEN PA.ESSERV = 0 THEN PR.DEsSeri ELSE 0 END) AS DESSERI, (CASE WHEN PA.ESSERV = 0 THEN PR.REFERE ELSE SR.CLASE END) 
                  AS REFERE, (CASE WHEN PA.ESSERV = 0 THEN PR.DESLOTE ELSE 0 END) AS DESLOTE, (CASE WHEN PA.ESSERV = 0 THEN PR.ESPESA ELSE 0 END) AS ESPESA, (CASE WHEN PA.ESSERV = 0 THEN PR.TARA ELSE 0 END) AS TARA, 
                  (CASE WHEN PA.ESSERV = 0 THEN 0 ELSE SR.USASERV END) AS USASERV, (CASE WHEN PA.ESSERV = 0 THEN PR.UNIDAD ELSE SR.UNIDAD END) AS UNIDAD, (CASE WHEN PA.ESSERV = 0 THEN PR.UNDEMPAQ ELSE NULL END) 
                  AS UNDEMPAQ, (CASE WHEN PA.ESSERV = 0 THEN PR.EXDECIMAL ELSE 0 END) AS EXDECIMAL
FROM     [dbo].SAPART PA LEFT JOIN
                  [dbo].SAPROD PR ON PA.CODALTE = PR.CODPROD LEFT JOIN
                  [dbo].SASERV SR ON PA.CODALTE = SR.CODSERV